In [29]:
import seaborn
import pandas 
import base
import observer
import attrib
import stores
import numpy
import geopandas
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import h5py

### Packages imported here are include the full list used for other charting examples, this notebook only uses h5py

**Enter the path to the datastore file you wish to view the groups and datasets within. For xKnowRes this is found in one of the run's subfolders.**

In [30]:
arrdat_path = 'E:\\Bayer\\bay.18\\models\\xKnowRes_20240315\\run\\TestRun_xKnowRes\\mcs\\X3WD9SKFALFH0YPN74\\store\\arr.dat'

# METHODS TO EXPLORE HDF5 WITH THIS NOTEBOOK:
## 1. Explore one group/dataset at a time (including its subgroups/datasets)
## 2. Skip to last chunk to view all groups and datasets within the arr.dat file as a scrollable list

## 1. Explore one group/dataset at a time (including its subgroups/datasets)


### Select data to access and enter one of the following options for data_primary variable.
### data_primary = "Dpu", "LandscapeScenario", "PPM", "Pearl", "Swap", or "Weather"

In [32]:
data_primary = "Pearl"

In [33]:

# Open the HDF5 file
with h5py.File(arrdat_path, 'r') as file:
    # Access the dataset group by name (replace data_primary variable to change this)
    dataset = file[data_primary]
    
    # Check if the dataset is a group or a dataset
    if isinstance(dataset, h5py.Group):
        # If group, access the members
        for name in dataset:
            subgroup = dataset[name]
            print(subgroup.name)  
            # Access subgroup's data or further subgroups if needed
    elif isinstance(dataset, h5py.Dataset):
        # If dataset, access directly
        data = dataset[:]
        print(data)

/Pearl/AmaUptPro
/Pearl/CropEmergence
/Pearl/CropHarvest
/Pearl/FlvLiqTrp
/Pearl/NumberOfParallelProcesses
/Pearl/ProcessingPath


### Now you can select a dataset to learn more about by choosing one of the names printed above to define the variable "data_secondary".
### Then access and print "data_secondary", the data type, as well as the dimensions

In [34]:
data_secondary = "AmaUptPro"

In [41]:
with h5py.File(arrdat_path, 'r') as file:
    
    group = file[data_primary]
    
    # Access a specific subgroup by its name (printed above, now defined as "data_secondary")
    subgroup_name = data_secondary  
    subgroup = group[subgroup_name]
    
    #access data or further subgroups within this subgroup
    if isinstance(subgroup, h5py.Dataset):
        data = subgroup[:]
        # Use the data as needed
        print(data)
        print(type(data))
        dimensions = data.shape
        print("Dimensions:", dimensions)

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 3.961e-11]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 8.220e-11]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 8.062e-11]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 8.302e-11]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 8.605e-11]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 1.886e-11]]
<class 'numpy.ndarray'>
Dimensions: (52, 2192)


## 2. Skip to last chunk to view all groups and datasets within the arr.dat file as a scrollable list

### View all of the groups and datasets by running the next chunk (see everything but the actual data values in the hdf5)
### Make sure to click "scrollable element" at the bottom of the printed result to avoid truncation

In [9]:
def print_hdf5_tree(hdf5_group, parent_group=''):
    for key in hdf5_group.keys():
        if isinstance(hdf5_group[key], h5py.Group):
            print(f"Group: {parent_group}/{key}")
            print_hdf5_tree(hdf5_group[key], f"{parent_group}/{key}")
        else:
            print(f"Dataset: {parent_group}/{key}")

with h5py.File(arrdat_path, 'r') as hdf5_file:
    print("HDF5 Tree Structure:")
    print_hdf5_tree(hdf5_file)

HDF5 Tree Structure:
Group: /Dpu
Dataset: /Dpu/ActualMassInFruits
Dataset: /Dpu/ActualMassInLeaves
Dataset: /Dpu/ActualMassInRoots
Dataset: /Dpu/ActualMassInStems
Dataset: /Dpu/ConcentrationInFruits
Dataset: /Dpu/ConcentrationInLeaves
Dataset: /Dpu/ConcentrationInRoots
Dataset: /Dpu/ConcentrationInStems
Dataset: /Dpu/CumulativeMassDegradationInFruits
Dataset: /Dpu/CumulativeMassDegradationInLeaves
Dataset: /Dpu/CumulativeMassDegradationInRoots
Dataset: /Dpu/CumulativeMassDegradationInStems
Dataset: /Dpu/CumulativeMassFluxIntoFruits
Dataset: /Dpu/CumulativeMassFluxIntoLeaves
Dataset: /Dpu/CumulativeMassFluxIntoRoots
Dataset: /Dpu/CumulativeMassFluxIntoStems
Dataset: /Dpu/CumulativeMassFluxOutOfFruits
Dataset: /Dpu/CumulativeMassFluxOutOfLeaves
Dataset: /Dpu/CumulativeMassFluxOutOfRoots
Dataset: /Dpu/CumulativeMassFluxOutOfStems
Dataset: /Dpu/CumulativeMassLossDueToPlantMaterialDecayInFruits
Dataset: /Dpu/CumulativeMassLossDueToPlantMaterialDecayInLeaves
Dataset: /Dpu/CumulativeMassLossD